server:
  port: 7000
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:properties/
#        git:
#          # 仓库地址
#          uri: https://github.com/xiaotiancai893661742/SpringCloud-Hello.git
#          # 对应 {label} 部分，即 Git 的分支
#          label: master
#          # 仓库文件夹名称，多个以逗号分隔
#          search-paths: config/env
#          # git 仓库用户名（公开库可以不用填写）
#          username: xiaotiancai893661742
#          # git 仓库密码（公开库可以不用填写）
#          password: lyc893661742

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
